#!/bin/sh
#------------------------------------------------
#      Centos7 Project Env InstallScript
#      copyright https://echat.oshit.com/
#      email: meyer_net@foxmail.com
#------------------------------------------------

function run()
{
	clear

	mkstart_lorsys

	return 0
}

function mkstart_lorsys()
{
	echo "--------------------------------------------------------------------"
	attDir=/clouddisk/attach
	supervisorConfigRoot=$attDir/supervisor
	
	sys_dir=$(pwd)
	
    #添加开机启动
	echo_startup_config $supervisorConfigRoot "lor-mysys" "$sys_dir" "sh start.sh master"

	#配置文件修改
	echo "LorSys: Please Ender Old OR Path To Refresh"
	read -e OLD_OR_PATH

	echo "LorSys: Please Ender New OR Path To Refresh"
	read -e NEW_OR_PATH

	sed -i "s@$OLD_OR_PATH@$NEW_OR_PATH@g" $sys_dir/conf/nginx-master.conf

	echo "--------------------------------------------------------------------"
	sh start.sh master
	echo "--------------------------------------------------------------------"
	echo "MkStart Over。"
}

#参数1：Supervisor的目录
#参数2：程序命名
#参数3：程序启动的目录
#参数4：程序启动的命令
function echo_startup_config()
{
	logDir=$1"/logs"
	scriptsDir=$1"/scripts"
	fileDir=$1"/conf/"

	mkdir -pv $logDir
	mkdir -pv $scriptsDir
	mkdir -pv $fileDir

	fileName=$2".conf"
	outputPath=${fileDir}${fileName}
	mkdir -pv $fileDir
	cat >$outputPath<<EOF
[program:$2]
directory = $3 ; 程序的启动目录
command = $4  ; 启动命令，可以看出与手动在命令行启动的命令是一样的
autostart = true     ; 在 supervisord 启动的时候也自动启动
startsecs = 60       ; 启动 60 秒后没有异常退出，就当作已经正常启动了
autorestart = true   ; 程序异常退出后自动重启
startretries = 3     ; 启动失败自动重试次数，默认是 3
user = root          ; 用哪个用户启动
redirect_stderr = true  ; 把 stderr 重定向到 stdout，默认 false
stdout_logfile_maxbytes = 20MB  ; stdout 日志文件大小，默认 50MB
stdout_logfile_backups = 20     ; stdout 日志文件备份数

stdout_logfile = $logDir/$2_stdout.log  ; stdout 日志文件，需要注意当指定目录不存在时无法正常启动，所以需要手动创建目录（supervisord 会自动创建日志文件）
numprocs=1           ;
EOF
}

run