#!/bin/bash
#------------------------------------------------
#      Centos7 Project Env InstallScript
#      copyright https://echat.oshit.com/
#      email: meyer_net@foxmail.com
#------------------------------------------------

rm -rf logs/*

WORK_PATH=`pwd`
source install/common.sh
source install/init_prj_config.sh
source install/init_svr_config.sh